[project]
name = "project-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=7.2.1",
    "groq>=0.14.0",
    "openai>=1.59.7",
    "phidata>=2.7.7",
    "yfinance>=0.2.51",
]
